updated workflow in the dev repository

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -74,7 +74,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: deploy
     steps:
-      - name: Checkout repo
+      - name: Checkout
         uses: actions/checkout@v4
       - name: Configure Git
         run: |
@@ -82,8 +82,10 @@ jobs:
           git config user.email "actions@github.com"
       - name: Push changes to production
         run: |
+          echo "Adding remote for production repository"
           git remote add prod https://robel-codes:${{ secrets.PROD_REPO_ACCESS_TOKEN }}@github.com/robel-codes/my-hugo-prod.git
-          git push prod main
+          echo "Pushing changes to production"
+          git push prod main || { echo "Push failed"; exit 1; }
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v4
         with:
